version: "3.7"
services:
  hexo-server:
    build: ../.
    image: hexo:latest
    container_name: hexo-deploy
    volumes:
      - "/d/docker/hexo/source:/home/hexo/source"
      - "/d/docker/hexo/themes:/home/hexo/themes"
      - "/d/docker/hexo/_config.yml:/home/hexo/_config.yml"
      - "/d/docker/hexo/ssh:/root/.ssh"
    command: chobon8 chobon@aliyun.com d
